version: '2'
services:
    geekmatcher-app:
        image: geekmatcher
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://geekmatcher-postgresql:5432/geekmatcher
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    geekmatcher-postgresql:
        extends:
            file: postgresql.yml
            service: geekmatcher-postgresql
